#!/bin/sh
# Install ports and some ancilary packages
echo "FirstBoot Script begun: `date +%c`
PERL_MINOR_VERSION=18;
/usr/sbin/portsnap fetch extract;
echo "Building Perl 5.$PERL_MINOR_VERSION and it's dependencies";
cd /usr/ports/lang/perl5.$PERL_MINOR_VERSION;
make config-recursive;
make install clean;
if [ $? -ne 0 ]; then
    echo "Perl or Dependency Failed To Build";
    echo "FirstBoot Script failed: `date +%c`
    exit 255;
fi
echo "Building portupgrade and it's dependencies";
cd /usr/ports/ports-mgmt/portupgrade;
make config-recursive;
make install clean;
if [ $? -ne 0 ]; then
    echo "Portupgrade or Dependency Failed To Build";
    echo "FirstBoot Script failed: `date +%c`
    exit 255;
fi
/usr/local/sbin/portinstall -Cfv -l $HOME/log/firstboot-`date +%F_%B` subversion git
if [ $? -ne 0 ]; then
    echo "Subversion, Git or Dependency Failed To Build";
    echo "FirstBoot Script failed: `date +%c"
    exit 255;
fi
echo "FirstBoot Script failed: `date +%c`
