#!/bin/sh
CBSD=$(which cbsd);
START=$(date +%c);
NOCOLOR=1

echo "Cleaning up the Jail Backups"
echo $START;

for JAIL in $(cbsd jorder);
    do echo $JAIL;
    $CBSD jsnapshot mode=destroy jname=${JAIL} snapname=${JAIL}_before_update;
    echo "Snapshot for ${JAIL} deleted: ";
    date +%c;
done;
