#!/bin/sh
# Run after the FreeBSD make world and kernel build/installs are done in makeworld.sh
# Best if run in Single User Mode.

cd /usr/src
$HOME/bin/installkernel

if [ $? -ne 0 ]; then
    echo "Failed installing the Kernel"
    exit 1;
fi; 

make installworld

if [ $? -ne 0 ]; then
    echo "Failed installing the World"
    exit 1;
fi; 

cd /usr/src/usr.sbin/mergemaster
/bin/sh mergemaster.sh -Uiv
echo "Install World Completed: Rebooting"
date +%c
fastboot
