#!/bin/sh
# Performs a Handbook make world:
# http://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/makeworld.html

echo "Beginning the make world process: $(date +%c)"
CPU=$(sysctl -n hw.ncpu); 
JOBS=$(( $CPU + 1 ));

cd /usr/src/usr.sbin/mergemaster
/bin/sh mergemaster.sh -pv
adjkerntz -i

cd /usr/src
make -j${JOBS} buildworld

if [ $? -ne 0 ]; then
    echo "Failed Compiling the World"
    exit 1;
fi; 

$HOME/bin/makekernel

if [ $? -ne 0 ]; then
    echo "Failed installing the Kernel"
    exit 1;
fi; 

echo "Build World, and Kernel Rebuilds Complete"
echo "Maybe boot into Single User Mode Now, and run $HOME/bin/installworld.sh to complete upgrade"
# shutdown now
