#!/bin/sh

echo "Kernel Build Begun: `date +%c`";
if [ "$#" -eq 0 ]; then
    KERNCONF=`uname -i`;
fi;
if [ "$#" -gt 0 ]; then
    KERNCONF=$1;
fi;
if [ "$KERNCONF" == "GENERIC" ]; then
    echo "Please choose the custom kernel";
    echo "Kernel Build Ended: `date +%c`";
    exit 255;
fi;
cd /usr/src
echo $KERNCONF;
make buildkernel KERNCONF=$KERNCONF;

echo "Kernel Build Ended: `date +%c`";
