#!/bin/sh
RELENG="stable";
VERSION="10";
#SVNHOST="svn.freebsd.org"
SVNHOST="svn0.us-west.freebsd.org"
SVNCMD="/usr/bin/svnlite";
if [ -x "/usr/local/bin/svn"]; then
    SVNCMD="/usr/local/bin/svn";
fi;
echo "Started: "
date +%c;
if [ -e "/usr/src/.svn" ]; then
    cd /usr/src/;
    $SVNCMD update;
else
    $SVNCMD checkout svn://$SVNHOST/base/$RELENG/$VERSION /usr/src;
fi;
echo "Finished: "
date +%c;
